language: ruby
rvm:
- 2.6.3
- 2.5.1
- 2.4.4
script: bundle exec rspec
before_install:
- gem update --system
deploy:
  provider: rubygems
  api_key:
    secure: PjXVYU8mWYMGlO50SsJg384hQb9Eb77F2jelMbtWeMQvBu4Yh4iegq9sWJbz9nlxQKluYIkHEkT+w1ZRZjODjVWpL9JVLaR4XX0jJ3DcgMN2omFIL0tbt4w8k9mXmtW63s1ZHB7uP4NL8u1rNWblkrRSRzgVPfv2sCJzyOkxgSmZVpfHXW21ed+CtqBZZPDXblOAZUzDCpn1duheCZodLZwlToZCvahCTEo0kjmW6ybeulltj1/jQzicKQMZIO2lM1YlFh1iIA9WxgzgSraJxsqTrS9ygaVOQjeAfMp3WYb5pdx6SozM5IH0MYIZMupVZaD3ojXnxYWLK41BsDlKyk8m1NbGZK7UxZWnFpeGjyxBzRFycVdX2jFqcyLxzyG0GzbEI7UOidlGM7M1JUGgnGMffrkGxAbtUlxlhEz5nfIs466Rq3f7DznK1rEJsEAN/iWnpqxxyVgAjN2OMez3Z3SiZo7S1K31ZIpkp2e9Md4ysDh4FqCV9SK4PdBqkSs36wo22kblUjY1xrBWmldFpbZypDSEU7QAurrmPZy/uBD7n06eWtWrGUC6fY89oQsnbclS3N9J6B8MGhNMxb9VDkqjUo2aD4I6WkDMWQTGpPFvmiiljWHGxDqwW1zwgRpSOwcLGDvEJarTQjOdhQO4EM5WGc1uJchFUm+snVEGYww=
  gem: secrets_parser
  on:
    tags: true
    repo: peertransfer/secrets_parser
